### ISSUE TITLE
Error when attempting to view assets

### ISSUE THREAD

**Issue by GuySartorelli** [gorriecoe/silverstripe-link#9]
I am getting an error when attempting to view assets (either at /admin/assets or with an UploadField if I click "Add from files"). The stack trace shows that the error is caused when the Link model tries to call "setName" on the scaffolder. Calling "getName" on the scaffolder before this shows that the name has already been set to "readLinks".

I believe this would be easily mitigated by wrapping the calls to "setName" inside if statements, checking hasMethod('setName'). If you agree, I will happily submit a pull request.

```
**Error:**
Object->__call(): the method 'setName' does not exist on 'SilverStripe\GraphQL\Scaffolding\Scaffolders\CRUD\Read'

**Stack trace:**
#0 /home/webspace/circini-ss4-dev1/site/vendor/gorriecoe/silverstripe-link/src/models/Link.php(368): SilverStripe\GraphQL\Scaffolding\Scaffolders\OperationScaffolder-&gt;__call('setName', Array)
#1 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/graphql/src/Manager.php(210): gorriecoe\Link\Models\Link-&gt;provideGraphQLScaffolding(Object(SilverStripe\GraphQL\Scaffolding\Scaffolders\SchemaScaffolder))
#2 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/graphql/src/Controller.php(103): SilverStripe\GraphQL\Manager::createFromConfig(Array)
#3 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/graphql/src/Controller.php(63): SilverStripe\GraphQL\Controller-&gt;getManager(Object(SilverStripe\Control\HTTPRequest))
#4 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/RequestHandler.php(319): SilverStripe\GraphQL\Controller-&gt;index(Object(SilverStripe\Control\HTTPRequest))
#5 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Controller.php(287): SilverStripe\Control\RequestHandler-&gt;handleAction(Object(SilverStripe\Control\HTTPRequest), 'index')
#6 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/RequestHandler.php(201): SilverStripe\Control\Controller-&gt;handleAction(Object(SilverStripe\Control\HTTPRequest), 'index')
#7 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Controller.php(212): SilverStripe\Control\RequestHandler-&gt;handleRequest(Object(SilverStripe\Control\HTTPRequest))
#8 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Director.php(361): SilverStripe\Control\Controller-&gt;handleRequest(Object(SilverStripe\Control\HTTPRequest))
#9 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/versioned/src/VersionedHTTPMiddleware.php(41): SilverStripe\Control\Director-&gt;SilverStripe\Control\{closure}(Object(SilverStripe\Control\HTTPRequest))
#10 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Versioned\VersionedHTTPMiddleware-&gt;process(Object(SilverStripe\Control\HTTPRequest), Object(Closure))
#11 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Security/BasicAuthMiddleware.php(68): SilverStripe\Control\Director-&gt;SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest))
#12 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Security\BasicAuthMiddleware-&gt;process(Object(SilverStripe\Control\HTTPRequest), Object(Closure))
#13 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Security/AuthenticationMiddleware.php(61): SilverStripe\Control\Director-&gt;SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest))
#14 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Security\AuthenticationMiddleware-&gt;process(Object(SilverStripe\Control\HTTPRequest), Object(Closure))
#15 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/CanonicalURLMiddleware.php(156): SilverStripe\Control\Director-&gt;SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest))
#16 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\CanonicalURLMiddleware-&gt;process(Object(SilverStripe\Control\HTTPRequest), Object(Closure))
#17 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/FlushMiddleware.php(26): SilverStripe\Control\Director-&gt;SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest))
#18 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\FlushMiddleware-&gt;process(Object(SilverStripe\Control\HTTPRequest), Object(Closure))
#19 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/RequestProcessor.php(66): SilverStripe\Control\Director-&gt;SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest))
#20 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\RequestProcessor-&gt;process(Object(SilverStripe\Control\HTTPRequest), Object(Closure))
#21 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/SessionMiddleware.php(20): SilverStripe\Control\Director-&gt;SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest))
#22 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\SessionMiddleware-&gt;process(Object(SilverStripe\Control\HTTPRequest), Object(Closure))
#23 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/AllowedHostsMiddleware.php(60): SilverStripe\Control\Director-&gt;SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest))
#24 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\AllowedHostsMiddleware-&gt;process(Object(SilverStripe\Control\HTTPRequest), Object(Closure))
#25 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/TrustedProxyMiddleware.php(176): SilverStripe\Control\Director-&gt;SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest))
#26 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\TrustedProxyMiddleware-&gt;process(Object(SilverStripe\Control\HTTPRequest), Object(Closure))
#27 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(65): SilverStripe\Control\Director-&gt;SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest))
#28 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Director.php(370): SilverStripe\Control\Director-&gt;callMiddleware(Object(SilverStripe\Control\HTTPRequest), Object(Closure))
#29 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/HTTPApplication.php(48): SilverStripe\Control\Director-&gt;handleRequest(Object(SilverStripe\Control\HTTPRequest))
#30 [internal function]: SilverStripe\Control\HTTPApplication-&gt;SilverStripe\Control\{closure}(Object(SilverStripe\Control\HTTPRequest))
#31 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/HTTPApplication.php(66): call_user_func(Object(Closure), Object(SilverStripe\Control\HTTPRequest))
#32 [internal function]: SilverStripe\Control\HTTPApplication-&gt;SilverStripe\Control\{closure}(Object(SilverStripe\Control\HTTPRequest))
#33 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Core/Startup/ErrorControlChainMiddleware.php(73): call_user_func(Object(Closure), Object(SilverStripe\Control\HTTPRequest))
#34 [internal function]: SilverStripe\Core\Startup\ErrorControlChainMiddleware-&gt;SilverStripe\Core\Startup\{closure}(Object(SilverStripe\Core\Startup\ErrorControlChain))
#35 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Core/Startup/ErrorControlChain.php(235): call_user_func(Object(Closure), Object(SilverStripe\Core\Startup\ErrorControlChain))
#36 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Core/Startup/ErrorControlChain.php(225): SilverStripe\Core\Startup\ErrorControlChain-&gt;step()
#37 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Core/Startup/ErrorControlChainMiddleware.php(92): SilverStripe\Core\Startup\ErrorControlChain-&gt;execute()
#38 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Core\Startup\ErrorControlChainMiddleware-&gt;process(Object(SilverStripe\Control\HTTPRequest), Object(Closure))
#39 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(65): SilverStripe\Control\HTTPApplication-&gt;SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest))
#40 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/HTTPApplication.php(67): SilverStripe\Control\HTTPApplication-&gt;callMiddleware(Object(SilverStripe\Control\HTTPRequest), Object(Closure))
#41 /home/webspace/circini-ss4-dev1/site/vendor/silverstripe/framework/src/Control/HTTPApplication.php(49): SilverStripe\Control\HTTPApplication-&gt;execute(Object(SilverStripe\Control\HTTPRequest), Object(Closure), false)
#42 /home/webspace/circini-ss4-dev1/site/public/index.php(25): SilverStripe\Control\HTTPApplication-&gt;handle(Object(SilverStripe\Control\HTTPRequest))
#43 {main}
```

**Comment by GuySartorelli** [comment]
I'm closing this - I can't reproduce it anymore.
